name: Build index from json and deploy

on:
  push:
    branches:
      - main
    paths:
      - 'data/**'
      - '!index.html'   # avoid infinite loop on index.html updates
  workflow_dispatch:    # allow manual trigger too

permissions:
  contents: read
  pages: write
  id-token: write


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jinja2 beautifulsoup4 openpyxl


      - name: Get changed files in the docs folder
        id: changed-files
        uses: tj-actions/changed-files@ed68ef82c095e0d48ec87eccea555d944a631a4c # v46
        with:
          files: |
            misa:
              - data/horarios-de-misa.md
            json:
              - data/web-repositorio.json
            excel:
              - data/web-repositorio.xlsx


      - name: misa file change
        # NOTE: Ensure all outputs are prefixed by the same key used above e.g. `test_(...)` | `doc_(...)` | `src_(...)` when trying to access the `any_changed` output.
        if: steps.changed-files.outputs.misa_any_changed == 'true'  
        run: |
          python main.py 'horarios-de-misa'
        working-directory: src/

      - name: excel file change
        if: steps.changed-files.outputs.excel_any_changed == 'true'  
        run: |
          python main.py 
        working-directory: src/

      - name: json file change
        if: steps.changed-files.outputs.json_any_changed == 'true'  && steps.changed-files.outputs.excel_any_changed == 'false'  
        run: |
          python main.py 'json-conf'
        working-directory: src/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public


  # Single deploy job since we're just deploying
  deploy:
    needs: build
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
